### ISSUE TITLE
Lo echamos a andar?

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/dorcas-s3-evaluacion-intermedia-smartsies#1]
A ver si este pequeño guión te ayuda?

1. Pasar el array por props a App
2. Desde App, en un UL, usar map para convertir el array de datos en un array de jsx, usando LI
3. Pasar por props los datos al componente de dicha de pokemoon
***
BONUS: Una vez hecho esto:  

1. Crear un componente PokemonList que pinte solo la lista de Pokemons, esto es: el ul, los li (con el atributo key="") y el componente de la card
2. Crear un componente PokemonCard para el componente de la card.

**Comment by smartsies** [comment]
Hola Carlos!

Pues creo que ya está. Hice una rama diferente para hacer el bonus, pero al hacer push lo hice a origin master en vez de a bonus, así que en master ahora aparece el bonus también.

También añadí la propiedad key a los lis en PokemonList, pero no estoy segura de para qué lo he hecho... En la consola aparecen al menos.

¡Gracias!
